name: Deploy
on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Bun setup
        uses: oven-sh/setup-bun@v1
      - run: bun install sharp --no-save

      - name: Build step
        run: "bun install && bun run build && rm -rf node_modules" # 📝 Update the build command(s) if necessary

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "jhonromero26"
          entrypoint: "server/entry.deno.js" # 📝 Update the entrypoint if necessary
          root: "." # 📝 Update the root if necessary
